# Jekyll configuration for Open SDG platform

# primary settings:
baseurl: "/herne-site" # change here!
remote_data_prefix: https://open-sdg-germany.usercontent.opencode.de/herne-data
# URL for the "Edit Data" and "Edit Metadata" button on indicators.
data_edit_url: http://prose.io/#OpenSDGde/herne-data/edit/develop/data/indicator_[id].csv
metadata_edit_url: http://prose.io/#OpenSDGde/herne-data/edit/develop/meta/[id].md

# Text zu Handlungsfelder
# fields to change: title, leitsatz, hf-goals
email_contacts:
  questions: fb-umweltundstadtplanung@herne.de
  suggestions: fb-umweltundstadtplanung@herne.de
  functional: fb-umweltundstadtplanung@herne.de

#
# other settings are alphabetically ordered:

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

cookie_consent_form:
  enabled: true

country:
  name: Herne
  adjective: Herne

create_indicators:
  layout: indicator
create_goals:
  previous_next_links: false
  goals: []
create_pages:
  - filename: ""
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ""
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ""
    folder: /search
    layout: search
    title: search.search

custom_js:
  - /assets/js/custom.js

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
  - .editorconfig
  - .gitmodules
  - data-repo/*
  - gitlab-ci.yml
  - .prettierrc
  - copy_handlungsfelder.sh
  - package-lock.json
  - package.json
  - tailwind.config.js
  - mise.toml
  - node_modules
  - _site
  - tmp
  - temp
  - '*.log'

footer_language_toggle: none

footer_menu:
  - path: https://StadtIngolstadt.github.io/sdg-data/de/zip/all_indicators.zip
    translation_key: Download
  - path: mailto:fb-umweltundstadtplanung@herne.de
    translation_key: menu.contact_us
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
  - path: /guidance
    translation_key: menu.guidance

frontpage_introduction_banner:
  title: my-custom-translations.frontpage-intro-title
  description: my-custom-translations.frontpage-intro-description

frontpage_goals_grid:
  title: my-custom-translations.my-goals-grid-title
  description: my-custom-translations.my-goals-grid-description

frontpage_cards:
  - title: Nachhaltigkeitsbericht - Stadt Herne 2023
    href: "https://www.herne.de/PDF/Klima/bnk_bericht_herne_final.pdf"
    thumbnail_src: /nachhaltigkeitsbericht.jpg
  - title: Nachhaltigkeitsstrategie - Stadt Herne 2021
    href: "https://www.herne.de/PDF/Umwelt/klima/lag_nhs_herne_gesamt_rz_web.pdf"
    thumbnail_src: /nachhaltigkeitsstrategie.jpg
  - title: Nachhaltigkeitskarte Stadt Herne
    href: "https://geoportal.herne.de/basis/?l=lernenundberatung%2Cnachhaltigereinkauf%2Cnachhaltigemobilitaet%2Creparierenstattwegwerfen%2Ctauscheundteilen%2Cwasserauffuellen%2Cschatten!%2CSitzgelegenheit!%2Ctoilette!%2Cwasser!%2Cstadtgebiet&bl=stadtplanwerkfarbegroup&t=klimamap&c=375736%2C5711250&s=39350"
    thumbnail_src: /HerneLogoWithBackground.jpeg

goal_image_base: https://open-sdg.org/sdg-translations/assets/img/goals
graph_color_set: accessible
header_language_toggle: dropdown

languages:
  - de

menu:
  - path: /
    translation_key: Startseite
  - path: /goals
    translation_key: general.goals
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /faq
    translation_key: menu.faq

menu_top:
  - path: /leichte-sprache
    translation_key: menu.plain_german
  - path: /reiter-english
    translation_key: English

metadata_tabs:
  - scope: national
    title: Metadaten
    description: indicator.national_metadata_blurb

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  - jekyll-tailwindcss

remote_theme: OpenSDGde/open-sdg@tpwd

title: general.site_title
url: ""
environment: staging

logos:
  - src: assets/img/LogoStadtHerneSlogan.png
    alt: "Stadt Herne Logo mit Slogan"
